----ANALYSIS OF THE INTERNATIONAL BREWERIES DATASET FROM 2017-2019 FOR AFRICAN COUNTRIES
--- PROFIT ANALYSIS --
--- COUNTRY ANALYSIS --
--- BRAND ANALYSIS ---
--- SALES REP ANALYSIS --

--OVERVIEW OF THE DATASET -- 
SELECT *
FROM [International_Breweries ]

SELECT DISTINCT(BRANDS)
FROM [International_Breweries ]

SELECT DISTINCT(YEARS)
FROM [International_Breweries ]

SELECT DISTINCT([REGION ])
FROM [International_Breweries ]

-- PROFIT ANALYSIS
--TOTAL PROFIT ACROSS ALL YEARS. 2017 - 2019
SELECT SUM(profit) AS Totl_Profit
FROM [International_Breweries ]

--TOTAL PROFIT ACROSS ALL FIVE COUNTRIES
SELECT COUNTRIES, SUM(profit) AS Total_Profit
FROM [International_Breweries ]
GROUP BY COUNTRIES
ORDER BY Total_Profit DESC

-- COUNTRY WITH THE HIGHEST PROFIT IN 2019
SELECT countries, SUM(profit) Total_profit
FROM [International_Breweries ]
WHERE years = '2019'
GROUP BY COUNTRIES
ORDER BY Total_profit DESC

-- COUNTRY WITH THE HIGHEST PROFIT IN 2018
SELECT countries, SUM(profit) Total_profit
FROM [International_Breweries ]
WHERE years = '2018'
GROUP BY COUNTRIES
ORDER BY Total_profit DESC

-- COUNTRY WITH THE HIGHEST PROFIT IN 2017
SELECT countries, SUM(profit) Total_profit
FROM [International_Breweries ]
WHERE years = '2017'
GROUP BY COUNTRIES
ORDER BY Total_profit DESC

-- TOTAL PROFIT ACROSS ALL YEARS 2017 - 2019
SELECT years, SUM(profit) AS Total_profit
FROM [International_Breweries ]
GROUP BY YEARS
ORDER BY Total_profit DESC

--PROFIT BY MONTHS
SELECT MONTHS, SUM(profit) AS year_profit
FROM [International_Breweries ]
GROUP BY  MONTHS
ORDER BY year_profit ASC

--MINIMUM PROFIT, NOT THE TOTAL PROFIT
SELECT MONTHS, MIN(profit) AS year_profit
FROM [International_Breweries ]
GROUP BY  MONTHS
ORDER BY year_profit ASC

--LEAST PROFIT IN DECEMBER, 2018
-- NB: FACT CHECK
SELECT MONTHS, MIN(profit) AS low_profit
FROM [International_Breweries ]
WHERE MONTHS = 'December' AND YEARS = '2018'
GROUP BY MONTHS
--ORDER BY low_profit DESC

--HIGHEST PROFIT FOR EACH BRAND
SELECT BRANDS, SUM(profit) AS Total_profit
FROM [International_Breweries ]
--WHERE COUNTRIES = 'Senegal'
GROUP BY   BRANDS
ORDER BY Total_profit DESC

SELECT MONTHS,  (SUM(Profit)/profit*100) AS percentage_profit
FROM [International_Breweries ]
WHERE YEARS = '2019'
GROUP BY MONTHS, PROFIT
ORDER BY percentage_profit DESC

--BRAND ANALYSIS
--TOTAL QUANTITY
SELECT SUM(QUANTITY) AS QUANTITY_B
FROM [International_Breweries ]

--TOTAL BRAND QUANTITY
SELECT  BRANDS, SUM(QUANTITY) AS Brand_Quantity
FROM [International_Breweries ]
GROUP BY  BRANDS
ORDER BY Brand_Quantity DESC

-- QUANTITY OF BRANDS CONSUMED IN FRANCOPHONE (FRENCH SPEAKING COUNTRIES)
SELECT  BRANDS, SUM(QUANTITY) AS Brand_Quantity
FROM [International_Breweries ]
--WHERE COUNTRIES IN ('Senegal', 'Togo', 'Benin')
GROUP BY  BRANDS
ORDER BY Brand_Quantity DESC

-- QUANTITY OF BRANDS CONSUMED IN ANGLOPHONE (ENGLISH SPEAKING COUNTRIES)
SELECT   BRANDS, SUM(QUANTITY) AS Brand_Quantity
FROM [International_Breweries ]
WHERE COUNTRIES NOT IN ('Senegal', 'Togo', 'Benin')
GROUP BY  BRANDS
ORDER BY Brand_Quantity DESC

-- TOTAL COST OF BRANDS
SELECT BRANDS, SUM(COST) AS Brand_Cost 
FROM [International_Breweries ]
GROUP BY BRANDS
ORDER BY Brand_Cost DESC

--QUANTITY OF BRANDS CONSUMED IN ALL COUNTRIES
SELECT  BRANDS, COUNTRIES, SUM(QUANTITY) AS Brand_Quantity
FROM [International_Breweries ]
GROUP BY BRANDS, COUNTRIES
ORDER BY Brand_Quantity 

--DETAILS OF BEER CONSUMED IN THE OIL MOST RICH COUNTRY IN WEST AFRICA, NIGERIA
SELECT *
FROM [International_Breweries ]
WHERE COUNTRIES IN ('Nigeria') AND BRANDS IN ('trophy','budweiser','hero', 'eagle lager')

---FAVORITE MALT BRANDS IN ANGLOPHONE SPEAKING COUNTRIES
SELECT BRANDS, COUNTRIES, SUM(QUANTITY) AS BrandQuantity
FROM [International_Breweries ]
WHERE YEARS IN ('2018', '2019') AND COUNTRIES IN ('Nigeria', 'Ghana')
GROUP BY BRANDS, COUNTRIES
HAVING BRANDS LIKE ('%malt%')
ORDER BY BrandQuantity DESC

--BRAND SALES IN NIGERIA, 2019
SELECT BRANDS, SUM(QUANTITY) AS BrandQuantity
FROM [International_Breweries ]
WHERE YEARS IN ('2019') AND COUNTRIES IN ('Nigeria')
GROUP BY BRANDS
ORDER BY BrandQuantity DESC

--FAVORITE BRAND IN SOUTH-SOUTH REGION OF NIGERIA
SELECT BRANDS,  SUM(QUANTITY) AS BrandQuantity
FROM [International_Breweries ]
WHERE COUNTRIES IN ('Nigeria')
GROUP BY BRANDS,  [REGION ]
HAVING [REGION ] = 'southsouth'
ORDER BY BrandQuantity DESC

--BRAND CONSUMPTION IN ALL REGIONS
SELECT  REGION,  SUM(QUANTITY) AS BrandQuantity
FROM [International_Breweries ]
GROUP BY [REGION ]
ORDER BY BrandQuantity DESC

--BEER CONSUMPTION IN NIGERIA
SELECT BRANDS,  SUM(QUANTITY) AS BrandQuantity
FROM [International_Breweries ]
WHERE BRANDS NOT LIKE ('%malt%')  AND COUNTRIES IN ('Nigeria')
GROUP BY BRANDS 
ORDER BY BrandQuantity DESC

--LEVEL OF CONSUMPTION OF BUDWEISER IN THE REGIONS OF NIGERIA
SELECT REGION, SUM(QUANTITY) AS BrandQuantity
FROM [International_Breweries ]
WHERE BRANDS = 'budweiser' AND COUNTRIES IN ('Nigeria')
GROUP BY [REGION ]
ORDER BY BrandQuantity DESC

--LEVEL OF CONSUMPTION OF BUDWEISER IN THE REGIONS OF NIGERIA, 2019
SELECT REGION, SUM(QUANTITY) AS BrandQuantity
FROM [International_Breweries ]
WHERE BRANDS = 'budweiser' AND COUNTRIES IN ('Nigeria') AND  YEARS IN ('2019')
GROUP BY [REGION ]
ORDER BY BrandQuantity DESC

----COUNTRIES ANALYSIS
--COUNTRY WITH THE HIHGEST CONSUMPTION OF BEER
SELECT COUNTRIES, SUM(QUANTITY) AS BrandQuantity
FROM [International_Breweries ]
WHERE BRANDS NOT LIKE ('%malt%') 
GROUP BY COUNTRIES
ORDER BY BrandQuantity DESC

--COUNTRIES WITH THE HIGHEST NUMBER OF PLANT COST
SELECT COUNTRIES, COUNT(PLANT_COST) NO_OF_PLANT
FROM [International_Breweries ]
GROUP BY COUNTRIES
ORDER BY NO_OF_PLANT DESC

--SUM OF TOTAL PLANT COST BY COUNTRY
SELECT COUNTRIES, SUM(PLANT_COST) Total_PLANT
FROM [International_Breweries ]
GROUP BY COUNTRIES
ORDER BY Total_PLANT DESC

--COUNTRY WITH THE HIGHEST QUANTITY OF BRANDS
SELECT COUNTRIES, SUM(QUANTITY) AS Quantity
FROM [International_Breweries ]
GROUP BY  COUNTRIES
ORDER BY Quantity DESC

--SALES REP ANALYSIS
--SLES REP THAT GENERATED THE HIGHEST PROFIT
SELECT SALES_REP, SUM(PROFIT) AS Sales_Profit 
FROM [International_Breweries ]
GROUP BY SALES_REP
ORDER BY Sales_Profit DESC

--SALES OF BUDWEISER IN SENEGAL
SELECT SALES_REP, SUM(PROFIT) AS Sales_Profit 
FROM [International_Breweries ]
WHERE BRANDS = 'budweiser' AND COUNTRIES = 'Senegal'
GROUP BY SALES_REP
ORDER BY Sales_Profit DESC

--SALES OF BUDWEISER IN NIGERIA
SELECT SALES_REP, SUM(PROFIT) AS Sales_Profit 
FROM [International_Breweries ]
WHERE BRANDS = 'budweiser' AND COUNTRIES = 'Nigeria'
GROUP BY SALES_REP
ORDER BY Sales_Profit DESC

--SALES REP WITH THE HIGHEST PROFIT IN THE LAST QUARTER OF 2019
SELECT SALES_REP, SUM(PROFIT) AS Country_Profit
FROM [International_Breweries ]
WHERE YEARS = '2019' AND MONTHS IN ('October', 'November', 'December')
GROUP BY SALES_REP
ORDER BY Country_Profit DESC

--THE END